spring:
  data:
      mongodb:
        host: localhost
        port: 27017
        database: NutriAi
        auto-index-creation: true





python:
  ai:
    url: http://127.0.0.1:5000/predict


